

parents: [d/mnist]
#parents: [d/celeba]
#parents: [d/celeba, deep]


#ckpt-step: 5

hidden-width: 64

lr: 0.001

#run-name: mnist_vae1_e-conv_d-conv_210910-135535

encoder: mnist_vae1_e-conv_d-conv_210910-135535

# debug

train-step: 10
val-step: 10

batch-size: 16

pbar: yes
name: 'test'




